### ISSUE TITLE
Not working on NVIDIA TX2 board

### ISSUE THREAD

**Issue by selalerer** [sahilparekh/GStreamer-Python#2]
Hi,

On NVIDIA TX2 it seems that this pipline (from vid_streamv3.py):

rtspsrc name=m_rtspsrc ! rtph264depay name=m_rtph264depay ! avdec_h264 name=m_avdech264 ! videoconvert name=m_videoconvert ! videorate name=m_videorate ! appsink name=m_appsink'

Doesn't work.

This pipeline works for me on the  command line to show on the screen so probably something more similar to that should be used:

rtspsrc location=rtsp://10.5.1.10/video1 ! queue ! decodebin ! videoconvert ! xvimagesin

Thank you, Sela.

**Comment by sahilparekh** [comment]
Hi Sela,

I have used it on NVIDIA NANO without issues. so if you can be more specific on error i can try to help.

**Comment by sahilparekh** [comment]
Did not listen from you since long time, so closing the issue.
